version: "3"
services:
        login-app:
            container_name: online-market
            image: latest123/online-market
            restart: always
            build: .
            ports:
              - "7500:7500"
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27018:27017'
