version: "3"
services:
  online-market:
    container_name: online-market
    image: "node:8"
    user: "node"
    restart: always
    build: .
    ports:
      - "80:3000" 
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
